config/routes.rb
Rails.application.routes.draw do
  root to: "home#index", as: 'root'
  get '/fetch_post' => 'home#fetch_post', as: 'fetch_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 20)
  end

  def fetch_post
    @post = Post.find(params[:post_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_post_body.html.erb
<div class="large-post">
  <img class="large-left-image" src="<%= post.image_url %>">
  <p class="large-post-text">Hi, I am feed post # <%= post.id %>. The date and time is <%= post.created_at %>. <%= post.body %></p>
</div>

app/views/home/fetch_post.js.erb
$('.fetch-post').html("<%= escape_javascript(render partial: 'post_body', locals: { post: @post }) %>");

app/views/home/index.html.erb
<nav class="header navbar navbar-default navbar-fixed-top">
  <h1>
    <%= link_to 'Social Feed Project', root_path %>
  </h1>
</nav>

<div id="posts" class="side-nav">
  <%= render @posts %>
</div>

<div class="body">
  <h1>Top 5 Post Topics</h1>
  <div class="mention">
    <p class="mention-name"></p>
  </div>
  <div class="mention">
    <p class="mention-name"></p>
  </div>
  <div class="mention">
    <p class="mention-name"></p>
  </div>
  <div class="mention">
    <p class="mention-name"></p>
  </div>
  <div class="mention">
    <p class="mention-name"></p>
  </div>

  <div class="fetch-post"></div>
</div>

<%= will_paginate @posts %>

app/views/home/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VisitWidgetProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/_post.html.erb
<% if post.id != 1 %>
  <hr>
<% end %>

<div class="feed-post<%= post.id == 1 ? ' top-post' : '' %>">
  <img class="left-image" src="<%= post.image_url %>">
  <p class="post-text">Hi, I am feed post # <%= post.id %>. The date and time is <%= post.created_at %>. 
  <%= link_to post.body, fetch_post_path(:post_id => post.id), method: :get, :remote => true, class: 'body-text' %></p>
</div>